#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Go lint and test
cd src/
golangci-lint run ./... --enable="gosec" --enable="golint" --enable="gofmt" --enable="goimports"
go test ./...
cd ../

# Terraform lint and doc generation
make tflint
make docs